version: "3.7"
services:
  nginx:
    container_name: anybooker_nginx
    env_file:
      - .env
    restart: unless-stopped
    build:
      context: ./nginx
    image: pesiok/anybooker-nginx
    ports:
      - $HOSTPORT:80
    depends_on:
      - frontend
      - backend

  database:
    container_name: database
    env_file:
      - .env
    image: postgres
    restart: unless-stopped
    volumes:
      - database_volume:/var/lib/postgresql/data

  backend:
    container_name: anybooker_backend
    env_file:
      - .env
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: pesiok/anybooker-backend
    depends_on:
      - database
    environment:
      - NODE_ENV=prod

  frontend:
    container_name: anybooker_frontend
    env_file:
      - .env
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: pesiok/anybooker-frontend

volumes:
  database_volume:
