version: "3.7"
services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - "3030:80"
    depends_on:
      - frontend
      - backend

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./backend

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./frontend
