version: "3.7"
services:
  backend:
    build:
      dockerfile: dev.Dockerfile
      context: ./backend
    volumes:
      - ./backend:/backend:delegated
      - /backend/node_modules
    environment:
      - NODE_ENV=dev

  database:
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"

  frontend:
    build:
      dockerfile: dev.Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/frontend:delegated
      - /frontend/node_modules
